### ISSUE TITLE
Callback when Egg is triggered

### ISSUE THREAD

**Issue by el1f** [devlato/react-easter#1]
It would be terrific to have a callback in order to customize the container easlier.

use case:
I want to hide the content of a page, replacing it with a pong board when the user inputs the correct code. Right now I can only pass the component to render so I could use a fullscreen modal to cover the content of the page but it would be even better to just set a state taht'd hide my components content while the egg is active. 

It could be something like:

```jsx
const EasterEgg = require('react-easter');

// ...

render() {
  return (
    <EasterEgg
        keys={/* Array of keys to type to trigger the easter egg */}
        simultaneous={/* Add this prop if keys should be pressed all together */}
        timeout={/* Duration to show your easter egg, easter egg is displayed forever if prop is not set */}
        onsuccess={/* Callback to call when the code is correctly inserted*/}
        ontimeout={/* Callback to call when the timer runs out*/}>
      {/* Your easter egg JSX goes here */}
    </EasterEgg>
  );
}
`

**Comment by el1f** [comment]
No intention on tackling this one @devlato?

**Comment by Angelk90** [comment]
@devlato , @el1f :
Are there any news about it?

**Comment by el1f** [comment]
It doesn't seem like the repo's actively maintained. You can use my fork as a dependency or modify it on your own in the meantime :)

**Comment by devlato** [comment]
Hey guys, I didn't have time for maintaining it. Will have a look this week 👍

**Comment by el1f** [comment]
So glad to see you back on this one @devlato! Take your time with it ;)

**Comment by gc** [comment]
Just found this project and I love it, its literally the exact thing I wanted - just sharing my support! Thanks

**Comment by devlato** [comment]
@gc thanks! 🙂

**Comment by Angelk90** [comment]
@devlato , @el1f :
Are there any news about it?

**Comment by devlato** [comment]
@Angelk90 will push the fix by the end of week, along with some other stuff 🙂
